# Contents: This script includes-
### 1. Importing libraries and necessary files
### 2. Data Wrangling 
####    -  Dropping columns
####    -  Dropping rows
####    -  Looking for missing values
####    -  Convertting the data types
####    -  Descriptive analysis
####    -   Checking for mixed data types
####    -   Checking for duplicate values
###  Exporting the Wrangled file

### Importing libraries and the customers data set

In [1]:
# Importing Libraries 
import pandas as pd
import numpy as np
import os

In [116]:
# Turning project folder path into a string
path=r'/Users/jasmeetakaur/Downloads/Jasmeeta/Data Immersion Course/Achievement 6'

In [117]:
# Importing the economic_profile.csv file
df_eco_profile=pd.read_csv(os.path.join(path,'profile_by_county_1969_2019.csv'),encoding = "ISO-8859-1", index_col = False)

/var/folders/77/3dq_7lv50b1b4jqj7g8kp0880000gn/T/ipykernel_13575/1164923666.py:2: DtypeWarning: Columns (2,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eco_profile=pd.read_csv(os.path.join(path,'profile_by_county_1969_2019.csv'),encoding = "ISO-8859-1", index_col = False)

## Data Wrangling

In [118]:
# Sanity testing the data frame contents
df_eco_profile.head(10)

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1969,1970,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,"""00000""",United States,,CAINC30,10.0,...,Personal income (thousands of dollars),Thousands of dollars,791229000,855525000,...,12541995000,13315478000,13998383000,14175503000,14982715000,15717140000,16151881000,16937582000,17839255000,18542262000
1,"""00000""",United States,,CAINC30,45.0,...,Net earnings by place of residence,Thousands of dollars,609767000,647228000,...,8044221000,8531667000,8956340000,9132669000,9539185000,9915088000,10145493000,10626821000,11167886000,11667012000
2,"""00000""",United States,,CAINC30,50.0,...,Personal current transfer receipts,Thousands of dollars,62322000,74733000,...,2325117000,2358654000,2362988000,2424297000,2541510000,2685370000,2776746000,2855049000,2970254000,3125174000
3,"""00000""",United States,,CAINC30,60.0,...,Income maintenance benefits 1/,Thousands of dollars,7275000,9897000,...,256034000,264137000,267614000,271171000,270971000,273685000,270259000,268468000,260380000,268682000
4,"""00000""",United States,,CAINC30,70.0,...,Unemployment insurance compensation,Thousands of dollars,2328000,4200000,...,139715000,107871000,84439000,63049000,35787000,32860000,32482000,30756000,28302000,28075000
5,"""00000""",United States,,CAINC30,80.0,...,Retirement and other,Thousands of dollars,52719000,60636000,...,1929368000,1986646000,2010935000,2090077000,2234752000,2378825000,2474005000,2555825000,2681572000,2828417000
6,"""00000""",United States,,CAINC30,90.0,...,"Dividends, interest, and rent 2/",Thousands of dollars,119140000,133564000,...,2172657000,2425157000,2679055000,2618537000,2902020000,3116682000,3229642000,3455712000,3701115000,3750076000
7,"""00000""",United States,,CAINC30,100.0,...,Population (persons) 3/,Number of persons,201298000,203798722,...,309321666,311556874,313830990,315993715,318301008,320635163,322941311,324985539,326687501,328239523
8,"""00000""",United States,,CAINC30,110.0,...,Per capita personal income 4/,Dollars,3931,4198,...,40547,42739,44605,44860,47071,49019,50015,52118,54606,56490
9,"""00000""",United States,,CAINC30,120.0,...,Per capita net earnings 4/,Dollars,3029,3176,...,26006,27384,28539,28901,29969,30923,31416,32699,34185,35544

In [106]:
df_eco_profile.describe()

           LineCode
count  99138.000000
mean     171.548387
std       82.234478
min       10.000000
25%      100.000000
50%      180.000000
75%      240.000000
max      310.000000

In [107]:
df_eco_profile.shape

(99142, 59)

In [14]:
df_eco_profile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99142 entries, 0 to 99141
Data columns (total 59 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   GeoFIPS                 99142 non-null  object
 1   GeoName                 99138 non-null  object
 2   Region                  99138 non-null  object
 3   TableName               99138 non-null  object
 4   LineCode                99138 non-null  float64
 5   IndustryClassification  99138 non-null  object
 6   Description             99138 non-null  object
 7   Unit                    99138 non-null  object
 8   1969                    99138 non-null  object
 9   1970                    99138 non-null  object
 10  1971                    99138 non-null  object
 11  1972                    99138 non-null  object
 12  1973                    99138 non-null  object
 13  1974                    99138 non-null  object
 14  1975                    99138 non-null  object
 15  1976                    99138 non-null  object
 16  1977                    99138 non-null  object
 17  1978                    99138 non-null  object
 18  1979                    99138 non-null  object
 19  1980                    99138 non-null  object
 20  1981                    99138 non-null  object
 21  1982                    99138 non-null  object
 22  1983                    99138 non-null  object
 23  1984                    99138 non-null  object
 24  1985                    99138 non-null  object
 25  1986                    99138 non-null  object
 26  1987                    99138 non-null  object
 27  1988                    99138 non-null  object
 28  1989                    99138 non-null  object
 29  1990                    99138 non-null  object
 30  1991                    99138 non-null  object
 31  1992                    99138 non-null  object
 32  1993                    99138 non-null  object
 33  1994                    99138 non-null  object
 34  1995                    99138 non-null  object
 35  1996                    99138 non-null  object
 36  1997                    99138 non-null  object
 37  1998                    99138 non-null  object
 38  1999                    99138 non-null  object
 39  2000                    99138 non-null  object
 40  2001                    99138 non-null  object
 41  2002                    99138 non-null  object
 42  2003                    99138 non-null  object
 43  2004                    99138 non-null  object
 44  2005                    99138 non-null  object
 45  2006                    99138 non-null  object
 46  2007                    99138 non-null  object
 47  2008                    99138 non-null  object
 48  2009                    99138 non-null  object
 49  2010                    99138 non-null  object
 50  2011                    99138 non-null  object
 51  2012                    99138 non-null  object
 52  2013                    99138 non-null  object
 53  2014                    99138 non-null  object
 54  2015                    99138 non-null  object
 55  2016                    99138 non-null  object
 56  2017                    99138 non-null  object
 57  2018                    99138 non-null  object
 58  2019                    99138 non-null  object
dtypes: float64(1), object(58)
memory usage: 44.6+ MB

### Step 1 - Dropping Columns 

#### Step 1.1 - Dropping unnecessary columns 
#### Assumption: Focussing on the latest 10 years of data for analysis.

In [113]:
df_eco_profile.head(10)

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1969,1970,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,"""00000""",United States,,CAINC30,10.0,...,Personal income (thousands of dollars),Thousands of dollars,791229000,855525000,...,12541995000,13315478000,13998383000,14175503000,14982715000,15717140000,16151881000,16937582000,17839255000,18542262000
1,"""00000""",United States,,CAINC30,45.0,...,Net earnings by place of residence,Thousands of dollars,609767000,647228000,...,8044221000,8531667000,8956340000,9132669000,9539185000,9915088000,10145493000,10626821000,11167886000,11667012000
2,"""00000""",United States,,CAINC30,50.0,...,Personal current transfer receipts,Thousands of dollars,62322000,74733000,...,2325117000,2358654000,2362988000,2424297000,2541510000,2685370000,2776746000,2855049000,2970254000,3125174000
3,"""00000""",United States,,CAINC30,60.0,...,Income maintenance benefits 1/,Thousands of dollars,7275000,9897000,...,256034000,264137000,267614000,271171000,270971000,273685000,270259000,268468000,260380000,268682000
4,"""00000""",United States,,CAINC30,70.0,...,Unemployment insurance compensation,Thousands of dollars,2328000,4200000,...,139715000,107871000,84439000,63049000,35787000,32860000,32482000,30756000,28302000,28075000
5,"""00000""",United States,,CAINC30,80.0,...,Retirement and other,Thousands of dollars,52719000,60636000,...,1929368000,1986646000,2010935000,2090077000,2234752000,2378825000,2474005000,2555825000,2681572000,2828417000
6,"""00000""",United States,,CAINC30,90.0,...,"Dividends, interest, and rent 2/",Thousands of dollars,119140000,133564000,...,2172657000,2425157000,2679055000,2618537000,2902020000,3116682000,3229642000,3455712000,3701115000,3750076000
7,"""00000""",United States,,CAINC30,100.0,...,Population (persons) 3/,Number of persons,201298000,203798722,...,309321666,311556874,313830990,315993715,318301008,320635163,322941311,324985539,326687501,328239523
8,"""00000""",United States,,CAINC30,110.0,...,Per capita personal income 4/,Dollars,3931,4198,...,40547,42739,44605,44860,47071,49019,50015,52118,54606,56490
9,"""00000""",United States,,CAINC30,120.0,...,Per capita net earnings 4/,Dollars,3029,3176,...,26006,27384,28539,28901,29969,30923,31416,32699,34185,35544

In [119]:
# Dropping columns from 1969 till 2009
df_eco_profile = df_eco_profile.drop(df_eco_profile.columns[8:49], axis=1)

#### 1.2 Verifying number of columns after deleting the extra years

In [120]:
df_eco_profile.head(10)

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,"""00000""",United States,,CAINC30,10.0,...,Personal income (thousands of dollars),Thousands of dollars,12541995000,13315478000,13998383000,14175503000,14982715000,15717140000,16151881000,16937582000,17839255000,18542262000
1,"""00000""",United States,,CAINC30,45.0,...,Net earnings by place of residence,Thousands of dollars,8044221000,8531667000,8956340000,9132669000,9539185000,9915088000,10145493000,10626821000,11167886000,11667012000
2,"""00000""",United States,,CAINC30,50.0,...,Personal current transfer receipts,Thousands of dollars,2325117000,2358654000,2362988000,2424297000,2541510000,2685370000,2776746000,2855049000,2970254000,3125174000
3,"""00000""",United States,,CAINC30,60.0,...,Income maintenance benefits 1/,Thousands of dollars,256034000,264137000,267614000,271171000,270971000,273685000,270259000,268468000,260380000,268682000
4,"""00000""",United States,,CAINC30,70.0,...,Unemployment insurance compensation,Thousands of dollars,139715000,107871000,84439000,63049000,35787000,32860000,32482000,30756000,28302000,28075000
5,"""00000""",United States,,CAINC30,80.0,...,Retirement and other,Thousands of dollars,1929368000,1986646000,2010935000,2090077000,2234752000,2378825000,2474005000,2555825000,2681572000,2828417000
6,"""00000""",United States,,CAINC30,90.0,...,"Dividends, interest, and rent 2/",Thousands of dollars,2172657000,2425157000,2679055000,2618537000,2902020000,3116682000,3229642000,3455712000,3701115000,3750076000
7,"""00000""",United States,,CAINC30,100.0,...,Population (persons) 3/,Number of persons,309321666,311556874,313830990,315993715,318301008,320635163,322941311,324985539,326687501,328239523
8,"""00000""",United States,,CAINC30,110.0,...,Per capita personal income 4/,Dollars,40547,42739,44605,44860,47071,49019,50015,52118,54606,56490
9,"""00000""",United States,,CAINC30,120.0,...,Per capita net earnings 4/,Dollars,26006,27384,28539,28901,29969,30923,31416,32699,34185,35544

#### 1.3 Dropping other unnecessary columns

In [121]:
# Dropping columns which are not informative
df_eco_profile = df_eco_profile.drop(columns = ['IndustryClassification', 'TableName', 'LineCode'])

In [123]:
df_eco_profile = df_eco_profile.drop(columns = ['Region'])

In [215]:
df_eco_profile = df_eco_profile.drop(columns = ['GeoFIPS'])

#### 1.4 Verifying the number of columns

In [216]:
df_eco_profile.head(10)

,GeoName,Description,Unit,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
62,"Autauga, AL",Personal income (thousands of dollars),Thousands of dollars,1826597.0,1896347.0,0.0,1944878.0,0.0,2131416.0,0.0,2276561.0,0.0,2453617.0
63,"Autauga, AL",Net earnings by place of residence,Thousands of dollars,0.0,1224272.0,1246525.0,1248619.0,1286995.0,1346348.0,1395861.0,1435492.0,0.0,1555278.0
64,"Autauga, AL",Personal current transfer receipts,Thousands of dollars,368849.0,391827.0,0.0,0.0,423992.0,0.0,472592.0,0.0,521491.0,0.0
65,"Autauga, AL",Income maintenance benefits 1/,Thousands of dollars,41957.0,44832.0,43347.0,44264.0,0.0,0.0,51131.0,49377.0,48821.0,51336.0
66,"Autauga, AL",Unemployment insurance compensation,Thousands of dollars,11248.0,9636.0,6747.0,4866.0,0.0,2343.0,2354.0,0.0,1887.0,1831.0
67,"Autauga, AL",Retirement and other,Thousands of dollars,315644.0,337359.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,488872.0
68,"Autauga, AL","Dividends, interest, and rent 2/",Thousands of dollars,267451.0,0.0,0.0,293126.0,0.0,319788.0,334828.0,339515.0,0.0,0.0
69,"Autauga, AL",Population (persons) 3/,Number of persons,54773.0,55227.0,54954.0,54727.0,54893.0,54864.0,55243.0,0.0,55533.0,55869.0
70,"Autauga, AL",Per capita personal income 4/,Dollars,33348.0,34337.0,0.0,35538.0,36786.0,38849.0,39883.0,0.0,0.0,43917.0
71,"Autauga, AL",Per capita net earnings 4/,Dollars,21731.0,22168.0,22683.0,22815.0,23446.0,0.0,25268.0,25916.0,26814.0,27838.0

### Step 2 - Dropping unnecessary rows that contain information about USA and the states
#### Assumption: We only want to work with the county data

#### 2.1 Printing the count of rows containing "United States"

In [241]:
df_eco_profile["GeoName"].str.contains('United States').value_counts(dropna=False)

GeoName
False    97557
Name: count, dtype: int64

#### 2.2 Printing the total number of rows

In [242]:
df_eco_profile.shape

(97557, 13)

#### 2.3 Deleting the count of rows containing "United States"

In [129]:
df_eco_profile =  df_eco_profile[~df_eco_profile["GeoName"].str.contains('United States', na = False)]

#### 2.4 Verify the count of rows containing "United States"

In [157]:
 #df_eco_profile["GeoName"].str.contains('United States').value_counts()
(df_eco_profile['GeoName']=='United States').value_counts()

GeoName
False    99111
Name: count, dtype: int64

#### 2.5 Verify the total count of rows after deleting rows containing "United States"

In [239]:
df_eco_profile.shape

(97557, 13)

#### 2.6 Printing the count of rows containing the name of the states

In [243]:
(df_eco_profile['GeoName'].isin(["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"])).value_counts()

GeoName
False    97557
Name: count, dtype: int64

#### 2.7 Printing the total number of rows

In [240]:
df_eco_profile.shape

(97557, 13)

#### 2.8 Delelting the count of rows containing only the states

In [175]:
df_eco_profile =  df_eco_profile[~df_eco_profile["GeoName"].isin(["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"])]

#### 2.9 Verify the count of rows containing the name of the states¶

In [244]:
#df_eco_profile['GeoName'].str.contains('Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming').value_counts()
(df_eco_profile['GeoName'].isin(["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"])).value_counts()

GeoName
False    97557
Name: count, dtype: int64

#### 2.10 Verify the total number of rows

In [252]:
df_eco_profile.shape

(97557, 13)

In [220]:
df_eco_profile.head(10)

,GeoName,Description,Unit,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
62,"Autauga, AL",Personal income (thousands of dollars),Thousands of dollars,1826597.0,1896347.0,0.0,1944878.0,0.0,2131416.0,0.0,2276561.0,0.0,2453617.0
63,"Autauga, AL",Net earnings by place of residence,Thousands of dollars,0.0,1224272.0,1246525.0,1248619.0,1286995.0,1346348.0,1395861.0,1435492.0,0.0,1555278.0
64,"Autauga, AL",Personal current transfer receipts,Thousands of dollars,368849.0,391827.0,0.0,0.0,423992.0,0.0,472592.0,0.0,521491.0,0.0
65,"Autauga, AL",Income maintenance benefits 1/,Thousands of dollars,41957.0,44832.0,43347.0,44264.0,0.0,0.0,51131.0,49377.0,48821.0,51336.0
66,"Autauga, AL",Unemployment insurance compensation,Thousands of dollars,11248.0,9636.0,6747.0,4866.0,0.0,2343.0,2354.0,0.0,1887.0,1831.0
67,"Autauga, AL",Retirement and other,Thousands of dollars,315644.0,337359.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,488872.0
68,"Autauga, AL","Dividends, interest, and rent 2/",Thousands of dollars,267451.0,0.0,0.0,293126.0,0.0,319788.0,334828.0,339515.0,0.0,0.0
69,"Autauga, AL",Population (persons) 3/,Number of persons,54773.0,55227.0,54954.0,54727.0,54893.0,54864.0,55243.0,0.0,55533.0,55869.0
70,"Autauga, AL",Per capita personal income 4/,Dollars,33348.0,34337.0,0.0,35538.0,36786.0,38849.0,39883.0,0.0,0.0,43917.0
71,"Autauga, AL",Per capita net earnings 4/,Dollars,21731.0,22168.0,22683.0,22815.0,23446.0,0.0,25268.0,25916.0,26814.0,27838.0

In [221]:
df_eco_profile.tail(10)

,GeoName,Description,Unit,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
99128,Far West,Farm proprietors' income,Thousands of dollars,8207952.0,12337611.0,13261484.0,15569912.0,17810889.0,18730273.0,14624620.0,13890846.0,13504574.0,16389718.0
99129,Far West,Nonfarm proprietors' income,Thousands of dollars,213194045.0,227751933.0,253471506.0,255493567.0,260673439.0,269081714.0,280366640.0,289691115.0,301873397.0,315954368.0
99130,Far West,Total employment (number of jobs),Number of jobs,28334630.0,28789094.0,29623593.0,30462053.0,31367082.0,32304848.0,33021135.0,33639261.0,34428969.0,35163035.0
99131,Far West,Wage and salary employment,Number of jobs,21787306.0,22005311.0,22785954.0,23426799.0,24093015.0,24775896.0,25366692.0,25838838.0,26408542.0,26854617.0
99132,Far West,Proprietors employment,Number of jobs,6547324.0,6783783.0,6837639.0,7035254.0,7274067.0,7528952.0,7654443.0,7800423.0,8020427.0,8308418.0
99133,Far West,Farm proprietors employment 6/,Number of jobs,143046.0,141475.0,138301.0,139622.0,137612.0,137750.0,135901.0,134831.0,133433.0,133776.0
99134,Far West,Nonfarm proprietors employment,Number of jobs,6404278.0,6642308.0,6699338.0,6895632.0,7136455.0,7391202.0,7518542.0,7665592.0,7886994.0,8174642.0
99135,Far West,Average earnings per job (dollars),Dollars,57498.0,59403.0,61230.0,61743.0,63144.0,65120.0,66436.0,68841.0,71048.0,73383.0
99136,Far West,Average wages and salaries,Dollars,51836.0,53438.0,54758.0,55106.0,56853.0,59226.0,60595.0,63262.0,65706.0,68428.0
99137,Far West,Average nonfarm proprietors' income,Dollars,33289.0,34288.0,37835.0,37052.0,36527.0,36406.0,37290.0,37791.0,38275.0,38651.0

#### 2.11 Deleting the last 4 rows containing metadata

In [180]:
df_eco_profile.drop(df_eco_profile.tail(4).index, inplace=True)

In [182]:
# Verifying the rows at the end of the data
df_eco_profile.tail(10)

,GeoFIPS,GeoName,Description,Unit,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
99128,"""98000""",Far West,Farm proprietors' income,Thousands of dollars,8207952.0,12337611.0,13261484.0,15569912.0,17810889.0,18730273.0,14624620.0,13890846.0,13504574.0,16389718.0
99129,"""98000""",Far West,Nonfarm proprietors' income,Thousands of dollars,213194045.0,227751933.0,253471506.0,255493567.0,260673439.0,269081714.0,280366640.0,289691115.0,301873397.0,315954368.0
99130,"""98000""",Far West,Total employment (number of jobs),Number of jobs,28334630.0,28789094.0,29623593.0,30462053.0,31367082.0,32304848.0,33021135.0,33639261.0,34428969.0,35163035.0
99131,"""98000""",Far West,Wage and salary employment,Number of jobs,21787306.0,22005311.0,22785954.0,23426799.0,24093015.0,24775896.0,25366692.0,25838838.0,26408542.0,26854617.0
99132,"""98000""",Far West,Proprietors employment,Number of jobs,6547324.0,6783783.0,6837639.0,7035254.0,7274067.0,7528952.0,7654443.0,7800423.0,8020427.0,8308418.0
99133,"""98000""",Far West,Farm proprietors employment 6/,Number of jobs,143046.0,141475.0,138301.0,139622.0,137612.0,137750.0,135901.0,134831.0,133433.0,133776.0
99134,"""98000""",Far West,Nonfarm proprietors employment,Number of jobs,6404278.0,6642308.0,6699338.0,6895632.0,7136455.0,7391202.0,7518542.0,7665592.0,7886994.0,8174642.0
99135,"""98000""",Far West,Average earnings per job (dollars),Dollars,57498.0,59403.0,61230.0,61743.0,63144.0,65120.0,66436.0,68841.0,71048.0,73383.0
99136,"""98000""",Far West,Average wages and salaries,Dollars,51836.0,53438.0,54758.0,55106.0,56853.0,59226.0,60595.0,63262.0,65706.0,68428.0
99137,"""98000""",Far West,Average nonfarm proprietors' income,Dollars,33289.0,34288.0,37835.0,37052.0,36527.0,36406.0,37290.0,37791.0,38275.0,38651.0

In [187]:
df_eco_profile.shape

(97557, 14)

### Step 3- Looking for missing values

In [184]:
df_eco_profile.isnull().sum()

GeoFIPS        0
GeoName        0
Description    0
Unit           0
2010           0
2011           0
2012           0
2013           0
2014           0
2015           0
2016           0
2017           0
2018           0
2019           0
dtype: int64

In [186]:
df_eco_profile.isna().sum()

GeoFIPS        0
GeoName        0
Description    0
Unit           0
2010           0
2011           0
2012           0
2013           0
2014           0
2015           0
2016           0
2017           0
2018           0
2019           0
dtype: int64

#### There were no missing values as such but on converting the year column values to float type it showed the presence of (NA) which could not be converted. So checking for the presence of (NA).

In [189]:
# Checking for (NA) values
(df_eco_profile['2010']=='(NA)').value_counts()

2010
False    96782
True       775
Name: count, dtype: int64

In [190]:
# Replacing all '(NA)' with 0
df_eco_profile.replace('(NA)',0, inplace=True,regex=True)

In [195]:
# Replacing all (0) with 0
df_eco_profile.replace('(0)',0, inplace=True,regex=True)

### Step 4 - describe() has only listed stats for one column. That clearly indicates that it is not able to identify the other columns that are supposed to have integer values.

### It is very likely that it identifies other integer columns as string.

#### Converting the data type of all the year columns to float

In [196]:
# 4.1 For 2010
df_eco_profile['2010'] = df_eco_profile['2010'].astype(float)

In [200]:
# Verifying for the changed data type 
df_eco_profile.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97557 entries, 62 to 99137
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoFIPS      97557 non-null  object
 1   GeoName      97557 non-null  object
 2   Description  97557 non-null  object
 3   Unit         97557 non-null  object
 4   2010         97557 non-null  float64
 5   2011         97557 non-null  object
 6   2012         97557 non-null  object
 7   2013         97557 non-null  object
 8   2014         97557 non-null  object
 9   2015         97557 non-null  object
 10  2016         97557 non-null  object
 11  2017         97557 non-null  object
 12  2018         97557 non-null  object
 13  2019         97557 non-null  object
dtypes: float64(1), object(13)
memory usage: 11.2+ MB

In [201]:
df_eco_profile['2011'] = df_eco_profile['2011'].astype(float)

In [202]:
df_eco_profile['2012'] = df_eco_profile['2012'].astype(float)

In [203]:
df_eco_profile['2013'] = df_eco_profile['2013'].astype(float)

In [204]:
df_eco_profile['2014'] = df_eco_profile['2014'].astype(float)

In [205]:
df_eco_profile['2015'] = df_eco_profile['2015'].astype(float)

In [206]:
df_eco_profile['2016'] = df_eco_profile['2016'].astype(float)

In [207]:
df_eco_profile['2017'] = df_eco_profile['2017'].astype(float)

In [208]:
df_eco_profile['2018'] = df_eco_profile['2018'].astype(float)

In [209]:
df_eco_profile['2019'] = df_eco_profile['2019'].astype(float)

### Verifying for the chaged data types

In [210]:
df_eco_profile.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97557 entries, 62 to 99137
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   GeoFIPS      97557 non-null  object
 1   GeoName      97557 non-null  object
 2   Description  97557 non-null  object
 3   Unit         97557 non-null  object
 4   2010         97557 non-null  float64
 5   2011         97557 non-null  float64
 6   2012         97557 non-null  float64
 7   2013         97557 non-null  float64
 8   2014         97557 non-null  float64
 9   2015         97557 non-null  float64
 10  2016         97557 non-null  float64
 11  2017         97557 non-null  float64
 12  2018         97557 non-null  float64
 13  2019         97557 non-null  float64
dtypes: float64(10), object(4)
memory usage: 11.2+ MB

### Step 5- Descriptive Statistical analysis for the first(2010) and last year(2019) of the period being analysed

In [222]:
# For 2010
df_eco_profile.groupby('Description').agg({'2010':['mean','max', 'min']})

                                                            2010  \
                                                            mean
Description
   Employer contributions for employee pension ...  6.186396e+05
   Employer contributions for government social...  2.727948e+05
   Farm proprietors' income                         2.612888e+04
   Nonfarm proprietors' income                      6.082167e+05
  Farm proprietors employment 6/                    1.150360e+03
  Income maintenance benefits 1/                    1.455128e+05
  Nonfarm proprietors employment                    2.061019e+04
  Per capita income maintenance benefits 4/         7.412361e+02
  Per capita retirement and other 4/                6.222129e+03
  Per capita unemployment insurance compensatio...  3.430289e+02
  Proprietors' income                               6.244150e+05
  Retirement and other                              1.118888e+06
  Supplements to wages and salaries                 8.741525e+05
  Unemployment insurance compensation               8.135403e+04
  Wages and salaries                                3.535373e+06
 Average nonfarm proprietors' income                2.122808e+04
 Average wages and salaries                         3.067902e+04
 Dividends, interest, and rent 2/                   1.215053e+06
 Earnings by place of work                          4.984044e+06
 Net earnings by place of residence                 4.486089e+06
 Per capita dividends, interest, and rent 4/        4.990776e+03
 Per capita net earnings 4/                         1.811791e+04
 Per capita personal current transfer receipts 4/   7.162096e+03
 Per capita personal income 4/                      2.995380e+04
 Personal current transfer receipts                 1.334900e+06
 Population (persons) 3/                            1.760606e+05
 Proprietors employment                             2.185852e+04
 Wage and salary employment                         7.763508e+04
Average earnings per job (dollars)                  3.493762e+04
Personal income (thousands of dollars)              6.977045e+06
Total employment (number of jobs)                   1.024084e+05


                                                             max       min
Description
   Employer contributions for employee pension ...  2.346006e+08       0.0
   Employer contributions for government social...  1.028417e+08       0.0
   Farm proprietors' income                         1.476697e+07  -69754.0
   Nonfarm proprietors' income                      2.131940e+08 -558774.0
  Farm proprietors employment 6/                    4.822280e+05       0.0
  Income maintenance benefits 1/                    6.740676e+07       0.0
  Nonfarm proprietors employment                    8.539731e+06       0.0
  Per capita income maintenance benefits 4/         3.373000e+03       0.0
  Per capita retirement and other 4/                1.289400e+04       0.0
  Per capita unemployment insurance compensatio...  1.326000e+03       0.0
  Proprietors' income                               2.214020e+08 -557223.0
  Retirement and other                              5.002891e+08       0.0
  Supplements to wages and salaries                 3.374423e+08       0.0
  Unemployment insurance compensation               3.191862e+07       0.0
  Wages and salaries                                1.403920e+09       0.0
 Average nonfarm proprietors' income                3.449680e+05   -6517.0
 Average wages and salaries                         1.008910e+05       0.0
 Dividends, interest, and rent 2/                   5.277503e+08       0.0
 Earnings by place of work                          1.945338e+09       0.0
 Net earnings by place of residence                 1.744919e+09       0.0
 Per capita dividends, interest, and rent 4/        8.779300e+04       0.0
 Per capita net earnings 4/                         7.773100e+04       0.0
 Per capita personal current transfer receipts 4/   1.517700e+04       0.0
 Per capita personal income 4/                      1.420030e+05       0.0
 Personal current transfer receipts                 5.931236e+08       0.0
 Population (persons) 3/                            7.857130e+07       0.0
 Proprietors employment                             9.021959e+06       0.0
 Wage and salary employment                         3.304378e+07       0.0
Average earnings per job (dollars)                  1.123420e+05       0.0
Personal income (thousands of dollars)              2.865793e+09       0.0
Total employment (number of jobs)                   4.206574e+07       0.0

In [223]:
# For 2019
df_eco_profile.groupby('Description').agg({'2019':['mean','max', 'min']})

                                                            2019  \
                                                            mean
Description
   Employer contributions for employee pension ...  8.272741e+05
   Employer contributions for government social...  3.693246e+05
   Farm proprietors' income                         3.314364e+04
   Nonfarm proprietors' income                      9.123182e+05
  Farm proprietors employment 6/                    1.090471e+03
  Income maintenance benefits 1/                    1.559092e+05
  Nonfarm proprietors employment                    2.680458e+04
  Per capita income maintenance benefits 4/         7.326285e+02
  Per capita retirement and other 4/                8.443574e+03
  Per capita unemployment insurance compensatio...  6.865364e+01
  Proprietors' income                               9.422319e+05
  Retirement and other                              1.630061e+06
  Supplements to wages and salaries                 1.187628e+06
  Unemployment insurance compensation               1.624775e+04
  Wages and salaries                                5.303177e+06
 Average nonfarm proprietors' income                2.326808e+04
 Average wages and salaries                         3.798354e+04
 Dividends, interest, and rent 2/                   2.091470e+06
 Earnings by place of work                          7.268612e+06
 Net earnings by place of residence                 6.512925e+06
 Per capita dividends, interest, and rent 4/        7.584757e+03
 Per capita net earnings 4/                         2.358496e+04
 Per capita personal current transfer receipts 4/   9.248057e+03
 Per capita personal income 4/                      4.077759e+04
 Personal current transfer receipts                 1.780161e+06
 Population (persons) 3/                            1.885827e+05
 Proprietors employment                             2.728408e+04
 Wage and salary employment                         9.092364e+04
Average earnings per job (dollars)                  4.169633e+04
Personal income (thousands of dollars)              1.036620e+07
Total employment (number of jobs)                   1.182693e+05


                                                             max      min
Description
   Employer contributions for employee pension ...  3.132275e+08      0.0
   Employer contributions for government social...  1.399364e+08      0.0
   Farm proprietors' income                         1.638972e+07 -57522.0
   Nonfarm proprietors' income                      3.181492e+08      0.0
  Farm proprietors employment 6/                    4.499620e+05      0.0
  Income maintenance benefits 1/                    6.973363e+07      0.0
  Nonfarm proprietors employment                    1.159913e+07      0.0
  Per capita income maintenance benefits 4/         3.527000e+03      0.0
  Per capita retirement and other 4/                1.954800e+04      0.0
  Per capita unemployment insurance compensatio...  6.720000e+02      0.0
  Proprietors' income                               3.323441e+08 -23695.0
  Retirement and other                              7.464592e+08      0.0
  Supplements to wages and salaries                 4.531639e+08      0.0
  Unemployment insurance compensation               7.190281e+06      0.0
  Wages and salaries                                2.008288e+09      0.0
 Average nonfarm proprietors' income                2.439930e+05      0.0
 Average wages and salaries                         1.372370e+05      0.0
 Dividends, interest, and rent 2/                   8.746314e+08      0.0
 Earnings by place of work                          2.767741e+09      0.0
 Net earnings by place of residence                 2.480127e+09      0.0
 Per capita dividends, interest, and rent 4/        1.614110e+05      0.0
 Per capita net earnings 4/                         1.202110e+05      0.0
 Per capita personal current transfer receipts 4/   2.173600e+04      0.0
 Per capita personal income 4/                      2.298250e+05      0.0
 Personal current transfer receipts                 8.189186e+08      0.0
 Population (persons) 3/                            8.490240e+07      0.0
 Proprietors employment                             1.204909e+07      0.0
 Wage and salary employment                         3.816968e+07      0.0
Average earnings per job (dollars)                  1.421670e+05      0.0
Personal income (thousands of dollars)              4.173677e+09      0.0
Total employment (number of jobs)                   5.021877e+07      0.0

In [245]:
# Trying descriptive analysis using groupby and describe together that gives the analysis for all the years
df_eco_profile.groupby('Description').describe()

                                                      2010                \
                                                     count          mean
Description
   Employer contributions for employee pension ...  3147.0  6.186396e+05
   Employer contributions for government social...  3147.0  2.727948e+05
   Farm proprietors' income                         3147.0  2.612888e+04
   Nonfarm proprietors' income                      3147.0  6.082167e+05
  Farm proprietors employment 6/                    3147.0  1.150360e+03
  Income maintenance benefits 1/                    3147.0  1.455128e+05
  Nonfarm proprietors employment                    3147.0  2.061019e+04
  Per capita income maintenance benefits 4/         3147.0  7.412361e+02
  Per capita retirement and other 4/                3147.0  6.222129e+03
  Per capita unemployment insurance compensatio...  3147.0  3.430289e+02
  Proprietors' income                               3147.0  6.244150e+05
  Retirement and other                              3147.0  1.118888e+06
  Supplements to wages and salaries                 3147.0  8.741525e+05
  Unemployment insurance compensation               3147.0  8.135403e+04
  Wages and salaries                                3147.0  3.535373e+06
 Average nonfarm proprietors' income                3147.0  2.122808e+04
 Average wages and salaries                         3147.0  3.067902e+04
 Dividends, interest, and rent 2/                   3147.0  1.215053e+06
 Earnings by place of work                          3147.0  4.984044e+06
 Net earnings by place of residence                 3147.0  4.486089e+06
 Per capita dividends, interest, and rent 4/        3147.0  4.990776e+03
 Per capita net earnings 4/                         3147.0  1.811791e+04
 Per capita personal current transfer receipts 4/   3147.0  7.162096e+03
 Per capita personal income 4/                      3147.0  2.995380e+04
 Personal current transfer receipts                 3147.0  1.334900e+06
 Population (persons) 3/                            3147.0  1.760606e+05
 Proprietors employment                             3147.0  2.185852e+04
 Wage and salary employment                         3147.0  7.763508e+04
Average earnings per job (dollars)                  3147.0  3.493762e+04
Personal income (thousands of dollars)              3147.0  6.977045e+06
Total employment (number of jobs)                   3147.0  1.024084e+05

                                                                            \
                                                             std       min
Description
   Employer contributions for employee pension ...  7.770760e+06       0.0
   Employer contributions for government social...  3.350875e+06       0.0
   Farm proprietors' income                         3.517995e+05  -69754.0
   Nonfarm proprietors' income                      7.578607e+06 -558774.0
  Farm proprietors employment 6/                    1.403794e+04       0.0
  Income maintenance benefits 1/                    1.894760e+06       0.0
  Nonfarm proprietors employment                    2.540531e+05       0.0
  Per capita income maintenance benefits 4/         4.090262e+02       0.0
  Per capita retirement and other 4/                2.424293e+03       0.0
  Per capita unemployment insurance compensatio...  1.856152e+02       0.0
  Proprietors' income                               7.812311e+06 -557223.0
  Retirement and other                              1.410673e+07       0.0
  Supplements to wages and salaries                 1.108405e+07       0.0
  Unemployment insurance compensation               1.025626e+06       0.0
  Wages and salaries                                4.551938e+07       0.0
 Average nonfarm proprietors' income                1.684709e+04   -6517.0
 Average wages and salaries                         1.318563e+04       0.0
 Dividends, interest, and rent 2/                   1.569795e+07       0.0
 Earnings by place of work                          6.442227e+07       0.0
 Net earnings by place of residence                 5.706345e+07       0.0
 Per capita dividends, interest, and rent 4/        3.441429e+03       0.0
 Per capita net earnings 4/                         9.250883e+03       0.0
 Per capita personal current transfer receipts 4/   2.931233e+03       0.0
 Per capita personal income 4/                      1.373331e+04       0.0
 Personal current transfer receipts                 1.699118e+07       0.0
 Population (persons) 3/                            2.236336e+06       0.0
 Proprietors employment                             2.654733e+05       0.0
 Wage and salary employment                         9.649338e+05       0.0
Average earnings per job (dollars)                  1.531020e+04       0.0
Personal income (thousands of dollars)              8.953801e+07       0.0
Total employment (number of jobs)                   1.234165e+06       0.0

                                                                        \
                                                         25%       50%
Description
   Employer contributions for employee pension ...   12125.0   41964.0
   Employer contributions for government social...    4552.0   16677.0
   Farm proprietors' income                              0.0    3466.0
   Nonfarm proprietors' income                       13675.0   40883.0
  Farm proprietors employment 6/                       238.0     459.0
  Income maintenance benefits 1/                      4356.0   17302.0
  Nonfarm proprietors employment                       790.5    2112.0
  Per capita income maintenance benefits 4/            516.0     716.0
  Per capita retirement and other 4/                  5638.0    6717.0
  Per capita unemployment insurance compensatio...     228.0     327.0
  Proprietors' income                                19111.0   54468.0
  Retirement and other                               44776.0  138378.0
  Supplements to wages and salaries                  16411.0   57804.0
  Unemployment insurance compensation                 1950.0    7158.0
  Wages and salaries                                 49615.0  191257.0
 Average nonfarm proprietors' income                 14830.0   19749.0
 Average wages and salaries                          28582.0   32299.0
 Dividends, interest, and rent 2/                    29594.5   85898.0
 Earnings by place of work                           88715.5  306000.0
 Net earnings by place of residence                  93542.0  327148.0
 Per capita dividends, interest, and rent 4/          3586.0    4701.0
 Per capita net earnings 4/                          14148.0   18361.0
 Per capita personal current transfer receipts 4/     6548.0    7831.0
 Per capita personal income 4/                       26800.5   31730.0
 Personal current transfer receipts                  47285.0  157356.0
 Population (persons) 3/                              6887.0   20839.0
 Proprietors employment                               1147.0    2713.0
 Wage and salary employment                           2099.0    6569.0
Average earnings per job (dollars)                   30962.5   36477.0
Personal income (thousands of dollars)              183171.5  576625.0
Total employment (number of jobs)                     3175.5    9223.0

                                                                             \
                                                          75%           max
Description
   Employer contributions for employee pension ...   137569.5  2.346006e+08
   Employer contributions for government social...    54417.0  1.028417e+08
   Farm proprietors' income                           16551.0  1.476697e+07
   Nonfarm proprietors' income                       119825.0  2.131940e+08
  Farm proprietors employment 6/                        761.0  4.822280e+05
  Income maintenance benefits 1/                      44974.0  6.740676e+07
  Nonfarm proprietors employment                       5665.5  8.539731e+06
  Per capita income maintenance benefits 4/             939.0  3.373000e+03
  Per capita retirement and other 4/                   7698.5  1.289400e+04
  Per capita unemployment insurance compensatio...      457.0  1.326000e+03
  Proprietors' income                                144432.0  2.214020e+08
  Retirement and other                               366149.5  5.002891e+08
  Supplements to wages and salaries                  189787.0  3.374423e+08
  Unemployment insurance compensation                 21774.0  3.191862e+07
  Wages and salaries                                 664330.0  1.403920e+09
 Average nonfarm proprietors' income                  25998.0  3.449680e+05
 Average wages and salaries                           36548.0  1.008910e+05
 Dividends, interest, and rent 2/                    262842.5  5.277503e+08
 Earnings by place of work                           962700.0  1.945338e+09
 Net earnings by place of residence                 1004412.5  1.744919e+09
 Per capita dividends, interest, and rent 4/           6292.0  8.779300e+04
 Per capita net earnings 4/                           22929.5  7.773100e+04
 Per capita personal current transfer receipts 4/      8933.0  1.517700e+04
 Per capita personal income 4/                        36752.5  1.420030e+05
 Personal current transfer receipts                  416027.5  5.931236e+08
 Population (persons) 3/                              54135.0  7.857130e+07
 Proprietors employment                                6345.5  9.021959e+06
 Wage and salary employment                           19761.0  3.304378e+07
Average earnings per job (dollars)                    42649.5  1.123420e+05
Personal income (thousands of dollars)              1717265.0  2.865793e+09
Total employment (number of jobs)                     26995.0  4.206574e+07

                                                      2011                ...  \
                                                     count          mean  ...
Description                                                               ...
   Employer contributions for employee pension ...  3147.0  6.302613e+05  ...
   Employer contributions for government social...  3147.0  2.913195e+05  ...
   Farm proprietors' income                         3147.0  4.211682e+04  ...
   Nonfarm proprietors' income                      3147.0  6.583448e+05  ...
  Farm proprietors employment 6/                    3147.0  1.136649e+03  ...
  Income maintenance benefits 1/                    3147.0  1.499407e+05  ...
  Nonfarm proprietors employment                    3147.0  2.189270e+04  ...
  Per capita income maintenance benefits 4/         3147.0  7.499990e+02  ...
  Per capita retirement and other 4/                3147.0  6.351459e+03  ...
  Per capita unemployment insurance compensatio...  3147.0  2.632126e+02  ...
  Proprietors' income                               3147.0  6.741656e+05  ...
  Retirement and other                              3147.0  1.140397e+06  ...
  Supplements to wages and salaries                 3147.0  9.047168e+05  ...
  Unemployment insurance compensation               3147.0  6.295716e+04  ...
  Wages and salaries                                3147.0  3.729090e+06  ...
 Average nonfarm proprietors' income                3147.0  2.186832e+04  ...
 Average wages and salaries                         3147.0  3.129780e+04  ...
 Dividends, interest, and rent 2/                   3147.0  1.397644e+06  ...
 Earnings by place of work                          3147.0  5.221473e+06  ...
 Net earnings by place of residence                 3147.0  4.821654e+06  ...
 Per capita dividends, interest, and rent 4/        3147.0  5.690834e+03  ...
 Per capita net earnings 4/                         3147.0  1.964860e+04  ...
 Per capita personal current transfer receipts 4/   3147.0  7.209337e+03  ...
 Per capita personal income 4/                      3147.0  3.247990e+04  ...
 Personal current transfer receipts                 3147.0  1.331455e+06  ...
 Population (persons) 3/                            3147.0  1.786728e+05  ...
 Proprietors employment                             3147.0  2.225529e+04  ...
 Wage and salary employment                         3147.0  7.756333e+04  ...
Average earnings per job (dollars)                  3147.0  3.682933e+04  ...
Personal income (thousands of dollars)              3147.0  7.356033e+06  ...
Total employment (number of jobs)                   3147.0  1.051490e+05  ...

                                                         2018                \
                                                          75%           max
Description
   Employer contributions for employee pension ...   169617.0  3.039117e+08
   Employer contributions for government social...    68336.0  1.339112e+08
   Farm proprietors' income                           13259.5  1.350457e+07
   Nonfarm proprietors' income                       155109.0  3.053691e+08
  Farm proprietors employment 6/                        718.0  4.525440e+05
  Income maintenance benefits 1/                      43756.5  6.802778e+07
  Nonfarm proprietors employment                       6396.5  1.123241e+07
  Per capita income maintenance benefits 4/             891.0  3.354000e+03
  Per capita retirement and other 4/                  10129.0  1.855300e+04
  Per capita unemployment insurance compensatio...       90.0  6.570000e+02
  Proprietors' income                                163995.0  3.153780e+08
  Retirement and other                               487652.5  7.073759e+08
  Supplements to wages and salaries                  241926.5  4.378229e+08
  Unemployment insurance compensation                  3853.0  7.153506e+06
  Wages and salaries                                 878820.5  1.921317e+09
 Average nonfarm proprietors' income                  28266.0  2.379250e+05
 Average wages and salaries                           44442.0  1.259580e+05
 Dividends, interest, and rent 2/                    395961.0  8.643932e+08
 Earnings by place of work                          1239408.5  2.653710e+09
 Net earnings by place of residence                 1285087.5  2.379675e+09
 Per capita dividends, interest, and rent 4/           9368.5  1.650420e+05
 Per capita net earnings 4/                           28490.5  1.151540e+05
 Per capita personal current transfer receipts 4/     11241.5  1.931000e+04
 Per capita personal income 4/                        47645.0  2.301410e+05
 Personal current transfer receipts                  541714.0  7.782079e+08
 Population (persons) 3/                              54714.5  8.429770e+07
 Proprietors employment                                7241.0  1.168495e+07
 Wage and salary employment                           21304.0  3.760045e+07
Average earnings per job (dollars)                    50146.0  1.387820e+05
Personal income (thousands of dollars)              2241389.5  4.022276e+09
Total employment (number of jobs)                     28087.0  4.928540e+07

                                                      2019                \
                                                     count          mean
Description
   Employer contributions for employee pension ...  3147.0  8.272741e+05
   Employer contributions for government social...  3147.0  3.693246e+05
   Farm proprietors' income                         3147.0  3.314364e+04
   Nonfarm proprietors' income                      3147.0  9.123182e+05
  Farm proprietors employment 6/                    3147.0  1.090471e+03
  Income maintenance benefits 1/                    3147.0  1.559092e+05
  Nonfarm proprietors employment                    3147.0  2.680458e+04
  Per capita income maintenance benefits 4/         3147.0  7.326285e+02
  Per capita retirement and other 4/                3147.0  8.443574e+03
  Per capita unemployment insurance compensatio...  3147.0  6.865364e+01
  Proprietors' income                               3147.0  9.422319e+05
  Retirement and other                              3147.0  1.630061e+06
  Supplements to wages and salaries                 3147.0  1.187628e+06
  Unemployment insurance compensation               3147.0  1.624775e+04
  Wages and salaries                                3147.0  5.303177e+06
 Average nonfarm proprietors' income                3147.0  2.326808e+04
 Average wages and salaries                         3147.0  3.798354e+04
 Dividends, interest, and rent 2/                   3147.0  2.091470e+06
 Earnings by place of work                          3147.0  7.268612e+06
 Net earnings by place of residence                 3147.0  6.512925e+06
 Per capita dividends, interest, and rent 4/        3147.0  7.584757e+03
 Per capita net earnings 4/                         3147.0  2.358496e+04
 Per capita personal current transfer receipts 4/   3147.0  9.248057e+03
 Per capita personal income 4/                      3147.0  4.077759e+04
 Personal current transfer receipts                 3147.0  1.780161e+06
 Population (persons) 3/                            3147.0  1.885827e+05
 Proprietors employment                             3147.0  2.728408e+04
 Wage and salary employment                         3147.0  9.092364e+04
Average earnings per job (dollars)                  3147.0  4.169633e+04
Personal income (thousands of dollars)              3147.0  1.036620e+07
Total employment (number of jobs)                   3147.0  1.182693e+05

                                                                           \
                                                             std      min
Description
   Employer contributions for employee pension ...  1.050928e+07      0.0
   Employer contributions for government social...  4.632845e+06      0.0
   Farm proprietors' income                         4.580582e+05 -57522.0
   Nonfarm proprietors' income                      1.151333e+07      0.0
  Farm proprietors employment 6/                    1.327773e+04      0.0
  Income maintenance benefits 1/                    2.006202e+06      0.0
  Nonfarm proprietors employment                    3.303089e+05      0.0
  Per capita income maintenance benefits 4/         4.092318e+02      0.0
  Per capita retirement and other 4/                3.817538e+03      0.0
  Per capita unemployment insurance compensatio...  5.284119e+01      0.0
  Proprietors' income                               1.185332e+07 -23695.0
  Retirement and other                              2.065503e+07      0.0
  Supplements to wages and salaries                 1.511942e+07      0.0
  Unemployment insurance compensation               2.075702e+05      0.0
  Wages and salaries                                6.691286e+07      0.0
 Average nonfarm proprietors' income                1.706202e+04      0.0
 Average wages and salaries                         1.682048e+04      0.0
 Dividends, interest, and rent 2/                   2.720588e+07      0.0
 Earnings by place of work                          9.338284e+07      0.0
 Net earnings by place of residence                 8.294024e+07      0.0
 Per capita dividends, interest, and rent 4/        6.021220e+03      0.0
 Per capita net earnings 4/                         1.248670e+04      0.0
 Per capita personal current transfer receipts 4/   4.144593e+03      0.0
 Per capita personal income 4/                      1.878081e+04      0.0
 Personal current transfer receipts                 2.282583e+07      0.0
 Population (persons) 3/                            2.374345e+06      0.0
 Proprietors employment                             3.411678e+05      0.0
 Wage and salary employment                         1.117784e+06      0.0
Average earnings per job (dollars)                  1.962963e+04      0.0
Personal income (thousands of dollars)              1.325711e+08      0.0
Total employment (number of jobs)                   1.461212e+06      0.0

                                                                        \

In [246]:
# Copying the above analysis result to clipboard
df_eco_profile.groupby('Description').describe().to_clipboard()

## Step 5- Complete the fundamental data quality and consistency checks

### 5.1 Objective: Checking for mixed data types

In [247]:
for col in df_eco_profile.columns.tolist():
  weird = (df_eco_profile[[col]].applymap(type) != df_eco_profile[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_eco_profile[weird]) > 0:
    print (col)

#### There are no mixed data types

### 5.2 Objective: Checking for duplicate values

In [250]:
df_dups = df_eco_profile[df_eco_profile.duplicated()]
df_dups

Empty DataFrame
Columns: [GeoName, Description, Unit, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
Index: []

### Insight: There are no duplicate values.

In [251]:
df_eco_profile.head(10)

,GeoName,Description,Unit,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
62,"Autauga, AL",Personal income (thousands of dollars),Thousands of dollars,1826597.0,1896347.0,0.0,1944878.0,0.0,2131416.0,0.0,2276561.0,0.0,2453617.0
63,"Autauga, AL",Net earnings by place of residence,Thousands of dollars,0.0,1224272.0,1246525.0,1248619.0,1286995.0,1346348.0,1395861.0,1435492.0,0.0,1555278.0
64,"Autauga, AL",Personal current transfer receipts,Thousands of dollars,368849.0,391827.0,0.0,0.0,423992.0,0.0,472592.0,0.0,521491.0,0.0
65,"Autauga, AL",Income maintenance benefits 1/,Thousands of dollars,41957.0,44832.0,43347.0,44264.0,0.0,0.0,51131.0,49377.0,48821.0,51336.0
66,"Autauga, AL",Unemployment insurance compensation,Thousands of dollars,11248.0,9636.0,6747.0,4866.0,0.0,2343.0,2354.0,0.0,1887.0,1831.0
67,"Autauga, AL",Retirement and other,Thousands of dollars,315644.0,337359.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,488872.0
68,"Autauga, AL","Dividends, interest, and rent 2/",Thousands of dollars,267451.0,0.0,0.0,293126.0,0.0,319788.0,334828.0,339515.0,0.0,0.0
69,"Autauga, AL",Population (persons) 3/,Number of persons,54773.0,55227.0,54954.0,54727.0,54893.0,54864.0,55243.0,0.0,55533.0,55869.0
70,"Autauga, AL",Per capita personal income 4/,Dollars,33348.0,34337.0,0.0,35538.0,36786.0,38849.0,39883.0,0.0,0.0,43917.0
71,"Autauga, AL",Per capita net earnings 4/,Dollars,21731.0,22168.0,22683.0,22815.0,23446.0,0.0,25268.0,25916.0,26814.0,27838.0

### Exporting the wrangled file

In [254]:
# Exporting the wrangled data frame
df_eco_profile.to_csv(os.path.join(path, 'eco_profile_clean.csv'))

## Backup

In [249]:
### Grouping by certain description criterion which are needed to answer the exploratory questions

grouped_df = df_eco_profile.groupby('Description')
descriptions_to_include = ['Retirement and other']

# Print unique values in 'Description' column
print("Unique Values in 'Description' column:", df_eco_profile['Description'].unique())

# Print intermediate results for debugging
for name, group in grouped_df:
    print(f"Group '{name}': {group}")

filtered_groups = grouped_df.filter(lambda group: any(category in descriptions_to_include for category in group['Description']))
print(filtered_groups)

grouped_df = df_eco_profile.groupby('Description')

descriptions_to_include = ['  Retirement and other']

filtered_groups = grouped_df.filter(lambda group: group['Description'].iloc[0] in descriptions_to_include)

print(filtered_groups)

Unique Values in 'Description' column: ['Personal income (thousands of dollars)'
 ' Net earnings by place of residence'
 ' Personal current transfer receipts' '  Income maintenance benefits 1/'
 '  Unemployment insurance compensation' '  Retirement and other'
 ' Dividends, interest, and rent 2/' ' Population (persons) 3/'
 ' Per capita personal income 4/' ' Per capita net earnings 4/'
 ' Per capita personal current transfer receipts 4/'
 '  Per capita income maintenance benefits 4/'
 '  Per capita unemployment insurance compensation 4/'
 '  Per capita retirement and other 4/'
 ' Per capita dividends, interest, and rent 4/'
 ' Earnings by place of work' '  Wages and salaries'
 '  Supplements to wages and salaries'
 '   Employer contributions for employee pension and insurance funds 5/'
 '   Employer contributions for government social insurance'
 "  Proprietors' income" "   Farm proprietors' income"
 "   Nonfarm proprietors' income" 'Total employment (number of jobs)'
 ' Wage and salary employment' ' Proprietors employment'
 '  Farm proprietors employment 6/' '  Nonfarm proprietors employment'
 'Average earnings per job (dollars)' ' Average wages and salaries'
 " Average nonfarm proprietors' income"]
Group '   Employer contributions for employee pension and insurance funds 5/':               GeoName                                        Description  \
80        Autauga, AL     Employer contributions for employee pension...
111       Baldwin, AL     Employer contributions for employee pension...
142       Barbour, AL     Employer contributions for employee pension...
173          Bibb, AL     Employer contributions for employee pension...
204        Blount, AL     Employer contributions for employee pension...
...               ...                                                ...
99001          Plains     Employer contributions for employee pension...
99032       Southeast     Employer contributions for employee pension...
99063       Southwest     Employer contributions for employee pension...
99094  Rocky Mountain     Employer contributions for employee pension...
99125        Far West     Employer contributions for employee pension...

                       Unit         2010         2011         2012  \
80     Thousands of dollars          0.0          0.0      63235.0
111    Thousands of dollars     332314.0     337777.0          0.0
142    Thousands of dollars      64811.0      63676.0          0.0
173    Thousands of dollars      31122.0      31421.0          0.0
204    Thousands of dollars      56854.0      55959.0          0.0
...                     ...          ...          ...          ...
99001  Thousands of dollars   70222038.0   71673692.0   71701717.0
99032  Thousands of dollars  234600638.0  232529456.0  239784022.0
99063  Thousands of dollars  108055267.0  108838125.0  113777774.0
99094  Thousands of dollars   33304573.0   33399364.0   34300290.0
99125  Thousands of dollars  195813324.0  207199135.0  208341081.0

              2013         2014         2015         2016         2017  \
80         65564.0      71495.0      74881.0      79156.0          0.0
111            0.0          0.0          0.0     418561.0     427891.0
142        58657.0          0.0      61385.0          0.0          0.0
173            0.0          0.0          0.0      34494.0          0.0
204        53829.0          0.0      58553.0          0.0          0.0
...            ...          ...          ...          ...          ...
99001   76278989.0   79792066.0   81642464.0   83105379.0   86930606.0
99032  251859506.0  260111246.0  268657420.0  273160869.0  285182898.0
99063  122808834.0  128341811.0  133762718.0  136739203.0  142920780.0
99094   37716464.0   38847736.0   40003481.0   41345408.0   43753459.0
99125  224502316.0  233286291.0  243648597.0  252806166.0  263243983.0

              2018         2019
80         83285.0      87974.0
111            0.0     488333.0
142        63786.0      64227.0
173            0.0      39868.0
204        63293.0      65618.0
...            ...          ...
99001   92912320.0   95192940.0
99032  303911696.0  313227501.0
99063  154122874.0  159994464.0
99094   47457852.0   49183581.0
99125  276082440.0  284977477.0

[3147 rows x 13 columns]
Group '   Employer contributions for government social insurance':               GeoName                                        Description  \
81        Autauga, AL     Employer contributions for government socia...
112       Baldwin, AL     Employer contributions for government socia...
143       Barbour, AL     Employer contributions for government socia...
174          Bibb, AL     Employer contributions for government socia...
205        Blount, AL     Employer contributions for government socia...
...               ...                                                ...
99002          Plains     Employer contributions for government socia...
99033       Southeast     Employer contributions for government socia...
99064       Southwest     Employer contributions for government socia...
99095  Rocky Mountain     Employer contributions for government socia...
99126        Far West     Employer contributions for government socia...

                       Unit         2010         2011         2012  \
81     Thousands of dollars      28864.0      29488.0      28684.0
112    Thousands of dollars          0.0          0.0     164462.0
143    Thousands of dollars      24879.0      25265.0      23998.0
174    Thousands of dollars      11866.0          0.0          0.0
205    Thousands of dollars          0.0          0.0      22285.0
...                     ...          ...          ...          ...
99002  Thousands of dollars   32154985.0   33732448.0   34983547.0
99033  Thousands of dollars  102841703.0  107583554.0  111741036.0
99064  Thousands of dollars   49769751.0   52944761.0   56053138.0
99095  Thousands of dollars   16814275.0   17945195.0   18763935.0
99126  Thousands of dollars   82599463.0   86936709.0   91061025.0

              2013         2014         2015         2016         2017  \
81         29165.0      29497.0          0.0      31626.0      32721.0
112       172152.0     179425.0          0.0     196249.0          0.0
143            0.0          0.0      23777.0      22547.0      22827.0
174        13149.0          0.0      12937.0      13288.0      13212.0
205            0.0      22378.0      22739.0      22935.0      23879.0
...            ...          ...          ...          ...          ...
99002   36103957.0   37195820.0   38549746.0   39008900.0   40228717.0
99033  114081321.0  118115350.0  123063827.0  125192730.0  129545108.0
99064   58064146.0   60621867.0   63284913.0   64252987.0   67367208.0
99095   19234588.0   20395749.0   21201049.0   21711723.0   22987216.0
99126   94282990.0   99111986.0  104835781.0  108894612.0  114319663.0

              2018         2019
81             0.0      36175.0
112       221648.0     237189.0
143            0.0          0.0
174        13596.0          0.0
205        25637.0      26286.0
...            ...          ...
99002   41362226.0   42722927.0
99033  133911242.0  139936373.0
99064   70046320.0   72819329.0
99095   23952929.0   25115553.0
99126  119444580.0  125440775.0

[3147 rows x 13 columns]
Group '   Farm proprietors' income':               GeoName                  Description                  Unit  \
83        Autauga, AL     Farm proprietors' income  Thousands of dollars
114       Baldwin, AL     Farm proprietors' income  Thousands of dollars
145       Barbour, AL     Farm proprietors' income  Thousands of dollars
176          Bibb, AL     Farm proprietors' income  Thousands of dollars
207        Blount, AL     Farm proprietors' income  Thousands of dollars
...               ...                          ...                   ...
99004          Plains     Farm proprietors' income  Thousands of dollars
99035       Southeast     Farm proprietors' income  Thousands of dollars
99066       Southwest     Farm proprietors' income  Thousands of dollars
99097  Rocky Mountain     Farm proprietors' income  Thousands of dollars
99128        Far West     Farm proprietors' income  Thousands of dollars

             2010        2011        2012        2013        2014        2015  \
83            0.0      7475.0         0.0     15925.0      6687.0         0.0
114           0.0     -3372.0       122.0     16125.0         0.0     -1838.0
145           0.0         0.0     14851.0     63794.0     33893.0     36156.0
176           0.0      1438.0      1771.0      5579.0      2414.0         0.0
207       15791.0     -9557.0      1611.0         0.0     45566.0     59176.0
...           ...         ...         ...         ...         ...         ...
99004  14766972.0  26561932.0  23913956.0  30753321.0  20372878.0  14453977.0
99035   6586476.0   7010388.0   9682209.0  17876614.0  12599900.0  12183966.0
99066   3337360.0   3875676.0   3471421.0   6580607.0   6429068.0   8121263.0
99097   1773267.0   3218452.0   2698094.0   3419414.0   3559499.0   3929947.0
99128   8207952.0  12337611.0  13261484.0  15569912.0  17810889.0  18730273.0

             2016        2017        2018        2019
83         7866.0     13158.0         0.0     12239.0
114         646.0      5196.0         0.0      8618.0
145       21737.0     27492.0         0.0     15878.0
176          73.0       622.0        -3.0      -238.0
207       24933.0     47882.0         0.0     15313.0
...           ...         ...         ...         ...
99004   9271021.0   7870764.0  10993292.0  15714403.0
99035   7071333.0  11929242.0   8645752.0   8301442.0
99066   3590920.0   4345602.0   4226771.0   4940008.0
99097   2544498.0   1350782.0   2184874.0   3547709.0
99128  14624620.0  13890846.0  13504574.0  16389718.0

[3147 rows x 13 columns]
Group '   Nonfarm proprietors' income':               GeoName                     Description                  Unit  \
84        Autauga, AL     Nonfarm proprietors' income  Thousands of dollars
115       Baldwin, AL     Nonfarm proprietors' income  Thousands of dollars
146       Barbour, AL     Nonfarm proprietors' income  Thousands of dollars
177          Bibb, AL     Nonfarm proprietors' income  Thousands of dollars
208        Blount, AL     Nonfarm proprietors' income  Thousands of dollars
...               ...                             ...                   ...
99005          Plains     Nonfarm proprietors' income  Thousands of dollars
99036       Southeast     Nonfarm proprietors' income  Thousands of dollars
99067       Southwest     Nonfarm proprietors' income  Thousands of dollars
99098  Rocky Mountain     Nonfarm proprietors' income  Thousands of dollars
99129        Far West     Nonfarm proprietors' income  Thousands of dollars

              2010         2011         2012         2013         2014  \
84         56176.0          0.0      81871.0          0.0      84678.0
115       319855.0          0.0          0.0          0.0          0.0
146        38758.0      31935.0      34635.0      33717.0      37727.0
177        26266.0      27628.0          0.0          0.0          0.0
208        82264.0          0.0     112262.0     115953.0          0.0
...            ...          ...          ...          ...          ...
99005   64277962.0   71433995.0   83302791.0   83116664.0   87159294.0
99036  197389519.0  211113308.0  233922092.0  225920437.0  247933314.0
99067  152154957.0  182283135.0  201315862.0  215892009.0  236673101.0
99098   28332470.0   33772599.0   38818714.0   47530522.0   53503063.0
99129  213194045.0  227751933.0  253471506.0  255493567.0  260673439.0

              2015         2016         2017         2018         2019
84         89688.0      89839.0          0.0          0.0      93543.0
115       541798.0          0.0     598229.0     638778.0          0.0
146            0.0      35825.0          0.0      39665.0          0.0
177            0.0      23618.0          0.0          0.0          0.0
208        96542.0      92453.0          0.0      96878.0          0.0
...            ...          ...          ...          ...          ...
99005   87324249.0   83581331.0   84455203.0   85248627.0   88672002.0
99036  251414648.0  256005591.0  269924523.0  285924342.0  297987514.0
99067  203268379.0  187003279.0  217777140.0  239567876.0  247870411.0
99098   52323496.0   49372902.0   55546831.0   60791215.0   62982704.0
99129  269081714.0  280366640.0  289691115.0  301873397.0  315954368.0

[3147 rows x 13 columns]
Group '  Farm proprietors employment 6/':               GeoName                       Description            Unit  \
88        Autauga, AL    Farm proprietors employment 6/  Number of jobs
119       Baldwin, AL    Farm proprietors employment 6/  Number of jobs
150       Barbour, AL    Farm proprietors employment 6/  Number of jobs
181          Bibb, AL    Farm proprietors employment 6/  Number of jobs
212        Blount, AL    Farm proprietors employment 6/  Number of jobs
...               ...                               ...             ...
99009          Plains    Farm proprietors employment 6/  Number of jobs
99040       Southeast    Farm proprietors employment 6/  Number of jobs
99071       Southwest    Farm proprietors employment 6/  Number of jobs
99102  Rocky Mountain    Farm proprietors employment 6/  Number of jobs
99133        Far West    Farm proprietors employment 6/  Number of jobs

           2010      2011      2012      2013      2014      2015      2016  \
88        357.0     356.0     345.0     351.0       0.0     337.0     339.0
119         0.0     881.0     833.0     844.0     817.0       0.0       0.0
150       522.0     519.0       0.0       0.0     485.0     475.0     473.0
181       176.0     174.0     165.0     166.0     159.0     155.0     154.0
212      1186.0    1162.0       0.0       0.0       0.0       0.0       0.0
...         ...       ...       ...       ...       ...       ...       ...
99009  381302.0  380465.0  375608.0  378343.0  369881.0  365718.0  360712.0
99040  482228.0  476501.0  463920.0  464965.0  463633.0  463481.0  461823.0
99071  335352.0  337845.0  336156.0  338329.0  338762.0  337327.0  338738.0
99102  104859.0  105511.0  103529.0  104148.0  105758.0  107068.0  107638.0
99133  143046.0  141475.0  138301.0  139622.0  137612.0  137750.0  135901.0

           2017      2018      2019
88        329.0     322.0     315.0
119       783.0     765.0     748.0
150       459.0     449.0     439.0
181       149.0     146.0     141.0
212         0.0       0.0     992.0
...         ...       ...       ...
99009  355425.0  354226.0  352912.0
99040  456148.0  452544.0  449962.0
99071  336120.0  333602.0  333500.0
99102  108115.0  107536.0  106923.0
99133  134831.0  133433.0  133776.0

[3147 rows x 13 columns]
Group '  Income maintenance benefits 1/':               GeoName                       Description                  Unit  \
65        Autauga, AL    Income maintenance benefits 1/  Thousands of dollars
96        Baldwin, AL    Income maintenance benefits 1/  Thousands of dollars
127       Barbour, AL    Income maintenance benefits 1/  Thousands of dollars
158          Bibb, AL    Income maintenance benefits 1/  Thousands of dollars
189        Blount, AL    Income maintenance benefits 1/  Thousands of dollars
...               ...                               ...                   ...
98986          Plains    Income maintenance benefits 1/  Thousands of dollars
99017       Southeast    Income maintenance benefits 1/  Thousands of dollars
99048       Southwest    Income maintenance benefits 1/  Thousands of dollars
99079  Rocky Mountain    Income maintenance benefits 1/  Thousands of dollars
99110        Far West    Income maintenance benefits 1/  Thousands of dollars

             2010        2011        2012        2013        2014        2015  \
65        41957.0     44832.0     43347.0     44264.0         0.0         0.0
96            0.0    114978.0         0.0    123562.0    126278.0    162379.0
127           0.0     37531.0     36979.0         0.0     35368.0     49484.0
158           0.0         0.0     22337.0     22196.0     21354.0     26925.0
189       42823.0         0.0         0.0     44421.0         0.0         0.0
...           ...         ...         ...         ...         ...         ...
98986  13804918.0  14010595.0  14253174.0  14440717.0  14258902.0  13955167.0
99017  67406757.0  70491504.0  71472053.0  72910256.0  71886195.0  72482134.0
99048  30126548.0  31235664.0  31528197.0  31936711.0  32020575.0  32218767.0
99079   6395476.0   6690307.0   6741510.0   6772450.0   6593714.0   6597043.0
99110  45464783.0  46854037.0  47125228.0  48026938.0  48697962.0  49615825.0

             2016        2017        2018        2019
65        51131.0     49377.0     48821.0     51336.0
96       156915.0    148932.0    147117.0    154656.0
127       47186.0     43466.0         0.0     43615.0
158       25673.0     24523.0         0.0     24388.0
189           0.0     47324.0     45742.0         0.0
...           ...         ...         ...         ...
98986  13720900.0  13487574.0  13147273.0  13750128.0
99017  71251743.0  70784536.0  68027778.0  69733633.0
99048  32217114.0  33091098.0  31462650.0  32673988.0
99079   6551165.0   6456388.0   6179075.0   6513539.0
99110  49723834.0  49773039.0  48229701.0  49946043.0

[3147 rows x 13 columns]
Group '  Nonfarm proprietors employment':               GeoName                       Description            Unit  \
89        Autauga, AL    Nonfarm proprietors employment  Number of jobs
120       Baldwin, AL    Nonfarm proprietors employment  Number of jobs
151       Barbour, AL    Nonfarm proprietors employment  Number of jobs
182          Bibb, AL    Nonfarm proprietors employment  Number of jobs
213        Blount, AL    Nonfarm proprietors employment  Number of jobs
...               ...                               ...             ...
99010          Plains    Nonfarm proprietors employment  Number of jobs
99041       Southeast    Nonfarm proprietors employment  Number of jobs
99072       Southwest    Nonfarm proprietors employment  Number of jobs
99103  Rocky Mountain    Nonfarm proprietors employment  Number of jobs
99134        Far West    Nonfarm proprietors employment  Number of jobs

            2010       2011       2012       2013       2014        2015  \
89        4652.0     4997.0        0.0     4623.0        0.0         0.0
120      24545.0    25725.0    26175.0    27273.0    28247.0     29266.0
151       1978.0        0.0     2547.0     2544.0     2636.0      2698.0
182       1547.0     1578.0     1519.0     1657.0     1595.0      1687.0
213       3655.0        0.0     3858.0     3855.0     3957.0      3881.0
...          ...        ...        ...        ...        ...         ...
99010  2364603.0  2447992.0  2445479.0  2483609.0  2518720.0   2548100.0
99041  8539731.0  9055366.0  9118673.0  9377268.0  9735709.0  10027156.0
99072  4602877.0  4819416.0  4920757.0  5078728.0  5226325.0   5388207.0
99103  1568121.0  1617239.0  1626687.0  1666626.0  1711959.0   1764877.0
99134  6404278.0  6642308.0  6699338.0  6895632.0  7136455.0   7391202.0

             2016        2017        2018        2019
89         4996.0      5238.0      5433.0      5583.0
120           0.0     32322.0     33995.0     34976.0
151        2537.0         0.0      2288.0      2351.0
182           0.0         0.0         0.0      1647.0
213        4664.0      4518.0      4869.0         0.0
...           ...         ...         ...         ...
99010   2572997.0   2584021.0   2634039.0   2716755.0
99041  10257452.0  10693943.0  11232406.0  11599129.0
99072   5553224.0   5789772.0   6015456.0   6183131.0
99103   1827467.0   1884887.0   1955873.0   2015371.0
99134   7518542.0   7665592.0   7886994.0   8174642.0

[3147 rows x 13 columns]
Group '  Per capita income maintenance benefits 4/':               GeoName                                  Description     Unit  \